
export const PAGE_LIST = [
    { label: "KPI Dashboard", value: "kpi-dashboard" },
    // { label: "Company", value: "company" },
    { label: "Machine MM", value: "machinemm" },
    { label: "Device OEE", value: "deviceoee" },
    { label: "Operation Analytics", value: "analytics" },
    // { label: "Component Analytics", value: "production-analysis" },
    { label: "Reports", value: "reports" },
    { label: "Operator Details", value: "operator-details" },
    { label: "Machines", value: "machines" },
    { label: "Machine Group", value: "machines-group" },
    { label: "Shift Registration", value: "shift-registration" },
    { label: "User Registration", value: "user-registration" },
    { label: "Group Registration", value: "group" },
    { label: "Component Registration", value: "component-registration" },
    { label: "Reason Registration", value: "reason-registration" },
    { label: "Group", value: "group" },
    { label: "Settings", value: "settings" },
    { label: "Production Metrics", value: "production-metrics" },
];

    // { label: "Operator Registration", value: "operator-registration" },

//   { label: "Andon Dashboard", value: "andon-dashboard" },
//   { label: "Shift", value: "shift" },
//   { label: "Machine Card", value: "machine-card" },//   { label: "Current Shift", value: "CurrentShift" },
//   { label: "Analytics", value: "analytics" },
//   { label: "Allocation", value: "allocation" },
//   { label: "Reports", value: "report" },
//   { label: "Machine Utilization", value: "machineutilization" },